<!DOCTYPE html>
<html>
<head>
    <title>MAGNIT</title>
</head>
<body>
<h1>MAGNIT</h1><a href="/">Главная</a><hr>
<h2>Авторизация</h2>
<form action="/login" method="post">
    Эл. почта: <input type="email" name="username"><br><br>
    Пароль: <input type="password" name="password"><br><br>
    <input type="submit" value="Вход">
</form>
<hr>
<a href="/register">Зарегистрироваться</a>
</body>
</html>